ng g c components/components-views/autocomplete-view
ng g c components/components-views/badge-view
ng g c components/components-views/bottom-sheet-view
ng g c components/components-views/button-view
ng g c components/components-views/button-toggle-view
ng g c components/components-views/card-view
ng g c components/components-views/checkbox-view
ng g c components/components-views/chips-view
ng g c components/components-views/core-view
ng g c components/components-views/datepicker-view
ng g c components/components-views/dialog-view
ng g c components/components-views/divider-view
ng g c components/components-views/expansion-panel-view
ng g c components/components-views/form-field-view
ng g c components/components-views/grid-list-view
ng g c components/components-views/icon-view
ng g c components/components-views/input-view
ng g c components/components-views/list-view
ng g c components/components-views/menu-view
ng g c components/components-views/paginator-view
ng g c components/components-views/progress-bar-view
ng g c components/components-views/progress-spinner-view
ng g c components/components-views/radio-button-view
ng g c components/components-views/ripples-view
ng g c components/components-views/select-view
ng g c components/components-views/sidenav-view
ng g c components/components-views/slide-toggle-view
ng g c components/components-views/slider-view
ng g c components/components-views/snackbar-view
ng g c components/components-views/sort-header-view
ng g c components/components-views/stepper-view
ng g c components/components-views/table-view
ng g c components/components-views/tabs-view
ng g c components/components-views/toolbar-view
ng g c components/components-views/tooltip-view
ng g c components/components-views/tree-view
echo 'FINISHED'