import { Component } from '@angular/core';
import {
  TableFlexBasicExample,
  TableBasicExample,
  TableDynamicColumnsExample,
  TableExpandableRowsExample,
  TableFilteringExample,
  TableFooterRowExample,
  TableHttpExample,
  TableMultipleHeaderFooterExample,
  TableOverviewExample,
  TablePaginationExample,
  TableRowContextExample,
  TableSelectionExample,
  TableSortingExample,
  TableStickyColumnsExample,
  TableStickyComplexFlexExample,
  TableStickyComplexExample,
  TableStickyFooterExample,
  TableStickyHeaderExample,
  TableTextColumnAdvancedExample,
  TableTextColumnExample,
  TableWrappedExample,
  WrapperTable,
  TableReorderableExample,
  TableRecycleRowsExample,
  TableHarnessExample,
  TableWithRipplesExample,
  TableColumnStylingExample,
  TableRowBindingExample,
  TableDynamicArrayDataExample,
  TableDynamicObservableDataExample,
  TableGeneratedColumnsExample,
  TableFlexLargeRowExample
} from '../index'

@Component({
  selector: 'app-table-view',
  templateUrl: './table-view.component.html',
  styleUrls: ['./table-view.component.css'],
  standalone:true,
  imports: [
    TableFlexBasicExample,
    TableBasicExample,
    TableDynamicColumnsExample,
    TableExpandableRowsExample,
    TableFilteringExample,
    TableFooterRowExample,
    TableHttpExample,
    TableMultipleHeaderFooterExample,
    TableOverviewExample,
    TablePaginationExample,
    TableRowContextExample,
    TableSelectionExample,
    TableSortingExample,
    TableStickyColumnsExample,
    TableStickyComplexFlexExample,
    TableStickyComplexExample,
    TableStickyFooterExample,
    TableStickyHeaderExample,
    TableTextColumnAdvancedExample,
    TableTextColumnExample,
    TableWrappedExample,
    WrapperTable,
    TableReorderableExample,
    TableRecycleRowsExample,
    TableHarnessExample,
    TableWithRipplesExample,
    TableColumnStylingExample,
    TableRowBindingExample,
    TableDynamicArrayDataExample,
    TableDynamicObservableDataExample,
    TableGeneratedColumnsExample,
    TableFlexLargeRowExample
  ]
  
})
export class TableViewComponent {

}
