export const componentNames: string[] = [
    'Autocomplete',
    'Badge',
    'Bottom Sheet',
    'Button',
    'Button toggle',
    'Card',
    'Checkbox',
    'Chips',
    'Core',
    'Datepicker',
    'Dialog',
    'Divider',
    'Expansion Panel',
    'Form field',
    'Grid list',
    'Icon',
    'Input',
    'List',
    'Menu',
    'Paginator',
    'Progress bar',
    'Progress spinner',
    'Radio button',
    'Ripples',
    'Select',
    'Sidenav',
    'Slide toggle',
    'Slider',
    'Snackbar',
    'Sort header',
    'Stepper',
    'Table',
    'Tabs',
    'Toolbar',
    'Tooltip',
    'Tree'
  ];
